package org.eipgrid.jql.sample.jpa.starwars.model;

import lombok.Getter;
import lombok.Setter;
import java.util.List;
import javax.persistence.*;
import io.hypersistence.utils.hibernate.type.json.JsonType;
import com.fasterxml.jackson.databind.node.ObjectNode;

/** This is generated by JQL-JDBC */

@Entity
@Table(name = "character", schema = "starwars_jpa", catalog = "starwars_jpa",
        uniqueConstraints = {
                @UniqueConstraint(name ="character_pkey", columnNames = {"id"})
        }
)
public class Character implements java.io.Serializable {
    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    Integer id;

    @Getter
    @Setter
    @Column(name = "species", nullable = false)
    String species;

    @Getter
    @Setter
    @Column(name = "name", nullable = false)
    String name;

    @Getter
    @Setter
    @Column(name = "height")
    Float height;

    @Getter
    @Setter
    @Column(name = "mass")
    Float mass;

    @Getter
    @Setter
    @Column(name = "metadata", columnDefinition = "json")
    @org.hibernate.annotations.Type(type = "io.hypersistence.utils.hibernate.type.json.JsonType")
    java.util.Map<String, Object> metadata;

    @Getter
    @Setter
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pilot")
    List<Starship> starship_;

    @Getter
    @Setter
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "character_episode_link", schema = "starwars_jpa", catalog = "starwars_jpa",
            uniqueConstraints = {
                    @UniqueConstraint(name = "character_id__episode_id__uindex", columnNames = {"character_id", "episode_id"})
            },
            joinColumns = @JoinColumn(name = "character_id"), inverseJoinColumns = @JoinColumn(name = "episode_id"))
    List<Episode> episode_;

    @Getter
    @Setter
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "character_friend_link", schema = "starwars_jpa", catalog = "starwars_jpa",
            uniqueConstraints = {
                    @UniqueConstraint(name = "character_id__friend_id__uindex", columnNames = {"character_id", "friend_id"})
            },
            joinColumns = @JoinColumn(name = "character_id"), inverseJoinColumns = @JoinColumn(name = "friend_id"))
    List<Character> friend_;
}