 name: JQL CI with Gradle

 on:
   push:
     branches: [ "ci-jest" ]

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout git
         uses: actions/checkout@v3

       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
           java-version: 17
           distribution: temurin

       - name: Set up node
         uses: actions/setup-node@v3
         with:
           node-version: 18

       - name: Build and run application
         working-directory: sample-app+tutorial
         run: | 
          sh db/start_postgres.sh
          ./gradlew bootRun --console=plain

       - name: Run jest integration tests
         working-directory: sample-app+tutorial/tutorial
         run: |
          npm install
          npm run test
