# name: JQL CI with Gradle

# on:
#   push:
#     branches: [ "ci-jest" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 11
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'temurin'
#       - name: Build Spring Application
#         working-directory: sample-app+tutorial
#         run: ./gradlew build
#       - name: Run Jest
#         working-directory:
